const _config = {
    API_KEY: process.env.EXPO_PUBLIC_FIREBASE_API_KEY,
    AUTH_DOMAIN: process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN,
    PROJECT_ID: process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID,
    STORAGE_BUCKET: process.env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET,
    MESSAGING_SENDER_ID: process.env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    APP_ID: process.env.EXPO_PUBLIC_FIREBASE_APP_ID,
    MEASURMENT_ID: process.env.EXPO_PUBLIC_FIREBASE_MEASURMENT_ID,
    BACKEND_API_SERVER: process.env.EXPO_PUBLIC_BACKEND_API_SERVER,
  };
  
  export const config = Object.freeze(_config);
  