const activationLinks = [
  { name: "ABC", link: "abc.com/activate" },
  { name: "A&E", link: "aetv.com/activate" },
  { name: "AMC", link: "amc.com/activate" },
  { name: "Animal Planet", link: "animalplanet.com/activate" },
  { name: "BBC America", link: "bbcamerica.com/activate" },
  { name: "BET", link: "bet.com/activate" },
  { name: "Big Ten Network", link: "btn.com/activate" },
  { name: "Bravo", link: "bravotv.com/activate" },
  { name: "Cartoon Network", link: "cartoonnetwork.com/activate" },
  { name: "CBS", link: "cbs.com/activate" },
  { name: "CINEMAX", link: "cinemax.com/activate" },
  { name: "CMT", link: "cmt.com/activate" },
  { name: "CNN", link: "cnn.com/activate" },
  { name: "Comedy Central", link: "cc.com/activate" },
  { name: "Cooking Channel", link: "cookingchanneltv.com/activate" },
  { name: "Discovery Channel", link: "go.discovery.com/activate" },
  { name: "Disney Channel", link: "disneynow.com/activate" },
  { name: "Disney Junior", link: "disneynow.com/activate" },
  { name: "Disney XD", link: "disneynow.com/activate" },
  { name: "DIY Network", link: "diynetwork.com/activate" },
  { name: "E!", link: "eonline.com/now/activate" },
  { name: "ESPN", link: "espn.com/activate" },
  { name: "ESPN2", link: "espn.com/activate" },
  { name: "Food Network", link: "watch.foodnetwork.com/activate" },
  { name: "FOX", link: "fox.com/activate" },
  { name: "Fox Business Network", link: "foxnews.com/activate" },
  { name: "Fox News Channel", link: "foxnews.com/activate" },
  { name: "FOX Sports 1", link: "foxsports.com/activate" },
  { name: "Freeform", link: "freeform.com/activate" },
  { name: "FX", link: "fxnetworks.com/activate" },
  { name: "FYI", link: "fyi.tv/activate" },
  { name: "Golf Channel", link: "golfchannel.com/activate" },
  { name: "Hallmark Channel", link: "hallmarkchanneleverywhere.com/activate" },
  { name: "HBO", link: "hbomax.com/activate" },
  { name: "HGTV", link: "watch.hgtv.com/activate" },
  { name: "History", link: "history.com/activate" },
  { name: "Investigation Discovery", link: "idgo.com/activate" },
  { name: "Lifetime", link: "mylifetime.com/activate" },
  { name: "MLB Network", link: "mlb.com/tv/activate" },
  { name: "MotorTrend", link: "motortrendondemand.com/activate" },
  { name: "MSNBC", link: "msnbc.com/activate" },
  { name: "MTV", link: "mtv.com/activate" },
  { name: "National Geographic", link: "nationalgeographic.com/tv/activate" },
  { name: "Nat Geo Wild", link: "nationalgeographic.com/tv/activate" },
  { name: "NBC", link: "nbc.com/activate" },
  { name: "NBC Sports Network", link: "nbcsports.com/activate" },
  { name: "NFL Network", link: "nfl.com/activate" },
  { name: "Nickelodeon", link: "nick.com/activate" },
  { name: "OWN", link: "oprah.com/own/activate" },
  { name: "Oxygen", link: "oxygen.com/activate" },
  { name: "Paramount Network", link: "paramountnetwork.com/activate" },
  { name: "PBS", link: "pbs.org/activate" },
  { name: "Science Channel", link: "sciencechannel.com/activate" },
  { name: "SHOWTIME", link: "showtimeanytime.com/activate" },
  { name: "STARZ", link: "starz.com/activate" },
  { name: "Sundance TV", link: "sundancetv.com/activate" },
  { name: "Syfy", link: "syfy.com/activate" },
  { name: "TBS", link: "tbs.com/activate" },
  { name: "Telemundo", link: "telemundo.com/activate" },
  { name: "The CW", link: "cwtv.com/activate" },
  { name: "The Weather Channel", link: "weathergroup.com/activate" },
  { name: "TLC", link: "tlc.com/activate" },
  { name: "TNT", link: "tntdrama.com/activate" },
  { name: "Travel Channel", link: "watch.travelchannel.com/activate" },
  { name: "truTV", link: "trutv.com/activate" },
  { name: "TV Land", link: "tvland.com/activate" },
  { name: "Univision", link: "univision.com/activate" },
  { name: "USA Network", link: "usanetwork.com/activate" },
  { name: "VH1", link: "vh1.com/activate" },
  { name: "WE tv", link: "wetv.com/activate" },
  { name: "netflix", link: "netflix.com/tv2" },
  { name: "disney+", link: "disneyplus.com/begin" },
  { name: "fubotv", link: "fubo.tv/connect" },
  { name: "peacocktv", link: "peacocktv.com/tv" },
  { name: "hbo max", link: "https://hbomax.com/activate" },
  { name: "espn+", link: "espn.com/activate" },
  { name: "paramount+", link: "different for every tv" },
  { name: "discovery+", link: "discoveryplus.in/activate" },
  { name: "youtube tv", link: "tv.youtube.com/start" },
  { name: "hulu", link: "hulu.com/activate" },
  { name: "philo tv", link: "philo.com/activate" },
  { name: "sling", link: "https://www.sling.com/sign-in/activate" },
  { name: "Amazon prime videos", link: "amazon.com/mytv" },
  { name: "Apple tv+", link: "https://activate.apple.com/" },
];

export { activationLinks };
